### ISSUE TITLE
lambda bug: AttributeError: 'PatternStr' object has no attribute 'raw'

### ISSUE THREAD

**Issue by TinyTakinTeller** [Scony/godot-gdscript-toolkit#263] opened 2024-01-06 18:06 UTC
this error 

```
'PatternStr' object has no attribute 'raw'
```

occurs when called on a file that contains this lambda

```
	enemies.sort_custom(func(a: Node2D, b: Node2D) -> bool:
		var distance_a: float = a.global_position.distance_squared_to(target.global_position) 
		var distance_b: float = b.global_position.distance_squared_to(target.global_position)
		return distance_a < distance_b
	)
```

full stack trace 

```
CENSORED>gdformat "CENSORED/scenes/ability/ability_controller/sword_ability_controller/sword_ability_controller.gd"
Traceback (most recent call last):
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\lexer.py", line 590, in lex
    yield lexer.next_token(lexer_state, parser_state)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\lexer.py", line 528, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\formatter\__main__.py", line 209, in _format_code
    code_parse_tree = parser.parse(code, gather_metadata=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\parser\parser.py", line 62, in parse
    self._parser_with_metadata.parse(adjusted_code)
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\parsers\lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\parsers\lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\parsers\lalr_parser.py", line 193, in parse_from_state
    raise e
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\parsers\lalr_parser.py", line 183, in parse_from_state
    for token in state.lexer.lex(state):
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\indenter.py", line 45, in _process
    for token in stream:
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\lexer.py", line 599, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\common\exceptions.py", line 14, in lark_unexpected_token_to_str
    return f"{exception.get_context(code)}\n{exception}"
                                            ^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
                ^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\lexer.py", line 124, in user_repr
    return self.pattern.raw or self.name
           ^^^^^^^^^^^^^^^^
AttributeError: 'PatternStr' object has no attribute 'raw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "CENSORED\AppData\Local\Programs\Python\Python312\Scripts\gdformat.exe\__main__.py", line 7, in <module>
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\formatter\__main__.py", line 78, in main
    _format_files(files, line_length, spaces_for_indent, safety_checks)
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\formatter\__main__.py", line 167, in _format_files
    success, actually_formatted, formatted_code = _format_code(
                                                  ^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\formatter\__main__.py", line 233, in _format_code
    lark_unexpected_token_to_str(
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\gdtoolkit\common\exceptions.py", line 16, in lark_unexpected_token_to_str
    return f"{exception}".strip()
             ^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
                ^^^^^^^^^^^^^^^^^^^^^
  File "CENSORED\AppData\Local\Programs\Python\Python312\Lib\site-packages\lark\lexer.py", line 124, in user_repr
    return self.pattern.raw or self.name
           ^^^^^^^^^^^^^^^^
AttributeError: 'PatternStr' object has no attribute 'raw'
```

**Comment by Scony** [comment] 2024-01-06 22:01
Duplicate of https://github.com/Scony/godot-gdscript-toolkit/issues/191 
As a side note, you can still use inline lambda, just write:
```
enemies.sort_custom(func(a: Node2D, b: Node2D) -> bool: return a.global_position.distance_squared_to(target.global_position) < b.global_position.distance_squared_to(target.global_position))
```
and it will be formatted to fairly good result

**Closed by Scony** 2024-01-06 22:01 UTC
