### ISSUE TITLE
`warning_ignore` annotation gets separated from function 

### ISSUE THREAD

**Issue by Kaifungamedev** [Scony/godot-gdscript-toolkit#279] opened 2024-01-26 17:02 UTC
As the title suggests, the `warning_ignore` annotation is moved two lines above a function. This doesn't sense make to me because it's directly related to that function.

**Comment by Scony** [comment] 2024-01-29 15:37
Duplicate of https://github.com/Scony/godot-gdscript-toolkit/issues/267

**Closed** 2024-03-21 21:21 UTC
