### ISSUE TITLE
godot4.3 support "is not" grammar, and will Cause an error

### ISSUE THREAD

**Issue by LuoXingHe** [Scony/godot-gdscript-toolkit#319] opened 2024-08-21 08:22 UTC
if code has **"if *** is not Class"** in godot4.3, will Cause an error.
and change to **"if not *** is Class"**, will be ok.

**Comment by Scony** [comment] 2024-08-21 20:38
Duplicate of https://github.com/Scony/godot-gdscript-toolkit/issues/318

**Closed by Scony** 2024-08-21 20:38 UTC
