### ISSUE TITLE
Linter doesn't like Godot 4.1 `@` annotations

### ISSUE THREAD

**Issue by madmachinations** [Scony/godot-gdscript-toolkit#230] opened 2023-09-13 13:50 UTC
I've upgraded to Godot 4.1 and upgraded the toolkit to the 4.1 version. I also have no gdlint file anywhere I can see. But when I run the linter, any scripts containing the new Godot 4 `@` style annotations throw an "Unexpected token" problem:

```
@warning_ignore("narrowing_conversion")
        ^

Unexpected token Token('AT', '@') at line 57, column 2.
Expected one of: 
	* LSQB
	* BIN
	* DOLLAR
	* LONG_STRING
	* AWAIT
	* CONST
	* MATCH
	* REGULAR_STRING
	* IF
	* FOR
	* FUNC
	* HEX
	* PLUS
	* TILDE
	* LPAR
	* BREAK
	* CONTINUE
	* CIRCUMFLEX
	* PERCENT
	* NAME
	* AMPERSAND
	* VAR
	* PASS
	* MINUS
	* BANG
	* RETURN
	* NUMBER
	* WHILE
	* LBRACE
	* NOT
Previous tokens: [Token('_NL', '\n\t')]

```

**Comment by madmachinations** [comment] 2023-09-13 14:46
This annotation was put in place by the Godot editor when I chose to ignore the warning. It was placed within a function body, indented - and this is what the linter doesn't like.

![image](https://github.com/Scony/godot-gdscript-toolkit/assets/14132673/939dc96c-b9d0-4de4-8e86-d90b90a0f2fc)

This creates sadness

![image](https://github.com/Scony/godot-gdscript-toolkit/assets/14132673/d86c84db-2d67-443f-ac20-077353cb0335)

Whereas this is fine

**Comment by Scony** [comment] 2023-09-13 15:35
Duplicate of: https://github.com/Scony/godot-gdscript-toolkit/issues/224

**Closed by Scony** 2023-09-13 15:35 UTC
