### ISSUE TITLE
Exception thrown when parsing Lambda functions

### ISSUE THREAD

**Issue by Skyway666** [Scony/godot-gdscript-toolkit#268] opened 2024-01-15 14:03 UTC
### Issue
Both the linter and parser tools correcly function when parsing **one line** Lambda functions. However, if the Lambda function is defined in **multiple lines**, an exception is thrown and the files remain unmodified.

![image](https://github.com/Scony/godot-gdscript-toolkit/assets/16372100/848eac88-95aa-42eb-a34c-b4be0d113faf)

### Steps to reproduce
Run gdlint or gdformat on the "lambda_function_test.gd" script, found in the attached sample project.

### Attatchments
The mentioned sample project "gdscript_toolkit_bug_lambda_functions" along with a .txt containing the error code given when attempting the mentioned steps to reproduce are compressed in the following .zip:

[gdscript_toolkit_bug_lambda_functions.zip](https://github.com/Scony/godot-gdscript-toolkit/files/13950059/gdscript_toolkit_bug_lambda_functions.zip)

**Comment by Scony** [comment] 2024-01-16 16:14
Duplicate of https://github.com/Scony/godot-gdscript-toolkit/issues/191

**Closed by Scony** 2024-01-16 16:14 UTC
