### ISSUE TITLE
GDFormat does not support static variable declaration

### ISSUE THREAD

**Issue by NancokPS2** [Scony/godot-gdscript-toolkit#255] opened 2023-11-28 16:22 UTC
Running "gdtoolkit==4.*"  
  
This line:  

`static var main_instance: SoundManager`  
  
  
Causes this error:  
  
```
SoundManager.gd:

static var main_instance: SoundManager
       ^

Unexpected token Token('VAR', 'var') at line 37, column 8.
Expected one of:
        * FUNC
Previous tokens: [Token('STATIC', 'static')]
0 files reformatted, 1 file left unchanged.
```  
    
------------------------------  

Link to the full offending script (Offending line is 37):  
https://github.com/NancokPS2/jdungeon/blob/unmute-game/scripts/classes/SoundManager.gd

**Comment by Scony** [comment] 2023-11-28 16:29
Duplicate of https://github.com/Scony/godot-gdscript-toolkit/issues/215 - this is fixed on `master` branch and will be part of next release.

If you need the solution immediately, please install latest gdtoolkit: https://github.com/Scony/godot-gdscript-toolkit#master-latest

**Closed by Scony** 2023-11-28 16:29 UTC
